In [1]:
import numpy as np

In [3]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])

In [4]:
a

array([[1., 2.],
       [3., 4.]])

In [5]:
a *= 10.0

In [6]:
a

array([[10., 20.],
       [30., 40.]])

In [7]:
b = a / 10.0

In [8]:
b

array([[1., 2.],
       [3., 4.]])

In [9]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
b[1,1] = 0.0

In [12]:
b

array([[1., 2.],
       [3., 0.]])

In [17]:
b.method

AttributeError: 'numpy.ndarray' object has no attribute 'method'

In [19]:
for x in dir(b):
    print(x)

T
__abs__
__add__
__and__
__array__
__array_finalize__
__array_interface__
__array_prepare__
__array_priority__
__array_struct__
__array_ufunc__
__array_wrap__
__bool__
__class__
__complex__
__contains__
__copy__
__deepcopy__
__delattr__
__delitem__
__dir__
__divmod__
__doc__
__eq__
__float__
__floordiv__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__iadd__
__iand__
__ifloordiv__
__ilshift__
__imatmul__
__imod__
__imul__
__index__
__init__
__init_subclass__
__int__
__invert__
__ior__
__ipow__
__irshift__
__isub__
__iter__
__itruediv__
__ixor__
__le__
__len__
__lshift__
__lt__
__matmul__
__mod__
__mul__
__ne__
__neg__
__new__
__or__
__pos__
__pow__
__radd__
__rand__
__rdivmod__
__reduce__
__reduce_ex__
__repr__
__rfloordiv__
__rlshift__
__rmatmul__
__rmod__
__rmul__
__ror__
__rpow__
__rrshift__
__rshift__
__rsub__
__rtruediv__
__rxor__
__setattr__
__setitem__
__setstate__
__sizeof__
__str__
__sub__
__subclasshook__
__truediv__
__xor__
all
any
argmax
argmin
argpartitio

In [25]:
b.shape

(2, 2)

In [26]:
?dir